feat: accept any Dev Env descriptor.
axem-solutions/dem pull request #141
Opened 2023-10-26 19:12 UTC by amathestar

### Checklist:

* [x] I have read and followed the [contribution guideline](https://github.com/axem-solutions/.github/blob/main/CONTRIBUTING.md).
* [x] I have checked to ensure there aren't other open Pull Requests for the same update/change
* [ ] I have tested these changes and added tests that prove my fix is effective or that my feature works
* [ ] I have made corresponding changes to the documentation
* [ ] New and existing unit tests pass locally with my changes
* [ ] 100% unit test coverage achieved

## Related Issue
Closing: 

## Type Of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Description

## How Has This Been Tested?

## Screenshots (if appropriate):

**Additional context**

2023-10-26 19:15 UTC, amathestar commented
Hi, Could you review the pull request for both commits

2023-10-27 09:00 UTC, janosmurai requested changes

2023-10-27 09:00 UTC, janosmurai commented on tests/core/test_dev_env.py
We still need the `test_DevEnv()` function as it is responsible for checking the correct instantiation.
Please delete the `test_DevEnv__check_tool_type_support()` instead, as you removed the `_check_tool_type_support()` function.

2023-10-27 10:47 UTC, janosmurai approved these changes

2023-10-27 11:39 UTC, janosmurai requested changes
Please remove all the references to the deleted `_check_tool_type_support()` method. 
All test cases must pass to approve a PR.

2023-10-28 10:45 UTC, closed without merging