Add export command to dem
axem-solutions/dem pull request #66
Opened 2023-07-31 18:21 UTC by magyta93

2023-08-01 14:03 UTC, janosmurai requested changes
The following options don't work (Assuming the Tutorial Dev Env is available):
`dem export Tutorial ~/test.json`
`dem export Tutorial`

2023-08-01 19:22 UTC, magyta93 commented on dem/cli/main.py
> +           path_to_export: str = typer.Argument(...,help="Path where to extract the Dev Env.")) -> None:
fixed

2023-08-01 19:23 UTC, magyta93 commented on dem/cli/command/export_cmd.py
> +def create_exported_dev_env_json(dev_env_name,dev_env_json,given_path):
fixed

2023-08-01 19:23 UTC, magyta93 commented on dem/cli/command/export_cmd.py
> +def check_is_file(param):
fixed

2023-08-01 19:23 UTC, magyta93 commented on tests/cli/test_export_cmd.py
fixed

2023-08-02 09:49 UTC, janosmurai approved these changes

2023-08-02 09:49 UTC, merged