The run command handles the docker CLI run command parameters.
axem-solutions/dem pull request #80
Opened 2023-09-05 13:15 UTC by janosmurai

Closes [DEM-140](https://axem.atlassian.net/browse/DEM-140)

2023-09-05 17:16 UTC, magyta93 commented on dem/core/container_engine.py
> +                        name = next(container_arguments_iter)
-d parameter process missing, to run container in background

2023-09-06 13:57 UTC, vezdeneszter requested changes

2023-09-06 20:07 UTC, magyta93 approved these changes

2023-09-06 20:08 UTC, magyta93 commented on dem/core/container_engine.py
> +        stream_logs = True
For me that way of the implementation is okay

2023-09-07 08:30 UTC, merged